# Enables the use of specific device descriptors for PlaceholderAPI
specific-device-descriptors: false

# The device strings for the placeholder
device:
  java: "Java"
  generic: "Bedrock"
  unknown: "Unknown"
  google: "Android"
  ios: "iOS"
  osx: "OSX"
  amazon: "Amazon"
  gearvr: "GearVR"
  hololens: "HoloLens"
  uwp: "UWP"
  win32: "Win32"
  dedicated: "DED"
  ps4: "PS4"
  nx: "Switch"
  xbox: "Xbox"

# The locale format (none for java users)
locale:
  found: "%locale%"
  none: "N/A"

# Bedrock version format (none for java users)
version:
  found: "%version%"
  none: "N/A"

# Xbox username format (none for java users)
xbox-username:
  found: "%username%"
  none: "%name%"

# Xbox xuid format (none for java users)
xbox-xuid:
  found: "%xuid%"
  none: "N/A"